### ISSUE TITLE
Question: MPD http socket directly (without websockfy)?

### ISSUE THREAD

**Issue by jehon** [bobboau/Bragi-MPD#16]
Hello dear developper of Bragi-MPD...

I wonder why it is necessary to use the websockify instead of using directly the mpd socket?

Thanks for your enlightment

**Comment by jehon** [comment]
I found it out myself, documenting it for reference.

Native socket are not supported anymore in browser. The socket need to be embedded into some http request. That is what webockify does.

**Comment by bobboau** [comment]
Yeah, sorry didnt answer sooner. For anyone else reading this thread the jist is basically websockets have a handshake that the server side has to handle properly to be websocket compliant. To remove the websockify dependency MPD would have to handle websocket handshake. Which is not a huge ask, might be doable.

**Comment by jehon** [comment]
For anyone coming here: the suggestion is here: https://github.com/MusicPlayerDaemon/MPD/issues/1511
