### ISSUE TITLE
Do I need a websockify instance for each MPD instance

### ISSUE THREAD

**Issue by owl770** [bobboau/Bragi-MPD#5]
Hi - apologies for the dumb question but if I have multiple instances of MPD running on multiple servers, do I need a separate instance of websockify for each MPD instance to be able to point it at the right host:port? Thanks.

**Comment by bobboau** [comment]
So far I have been using one websockify instance per mpd instance. There might be a way to run one websockify instance for multiple mpd instances but I have not experimented with that. If you get it working let me know.
